# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientDialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_clientDialog(object):
    def setupUi(self, clientDialog):
        clientDialog.setObjectName("clientDialog")
        clientDialog.resize(363, 311)
        self.verticalLayout = QtWidgets.QVBoxLayout(clientDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.clientTypeComboBox = QtWidgets.QComboBox(clientDialog)
        self.clientTypeComboBox.setObjectName("clientTypeComboBox")
        self.clientTypeComboBox.addItem("")
        self.clientTypeComboBox.addItem("")
        self.verticalLayout.addWidget(self.clientTypeComboBox)
        self.companyWidget = QtWidgets.QWidget(clientDialog)
        self.companyWidget.setObjectName("companyWidget")
        self.formLayout = QtWidgets.QFormLayout(self.companyWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.cmpNameLabel = QtWidgets.QLabel(self.companyWidget)
        self.cmpNameLabel.setObjectName("cmpNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cmpNameLabel)
        self.cmpNameLineEdit = QtWidgets.QLineEdit(self.companyWidget)
        self.cmpNameLineEdit.setObjectName("cmpNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmpNameLineEdit)
        self.cmpNIPLabel = QtWidgets.QLabel(self.companyWidget)
        self.cmpNIPLabel.setObjectName("cmpNIPLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cmpNIPLabel)
        self.cmpNIPLineEdit = QtWidgets.QLineEdit(self.companyWidget)
        self.cmpNIPLineEdit.setObjectName("cmpNIPLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmpNIPLineEdit)
        self.cmpAddressLabel = QtWidgets.QLabel(self.companyWidget)
        self.cmpAddressLabel.setObjectName("cmpAddressLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cmpAddressLabel)
        self.cmpAddressLineEdit = QtWidgets.QLineEdit(self.companyWidget)
        self.cmpAddressLineEdit.setObjectName("cmpAddressLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmpAddressLineEdit)
        self.verticalLayout.addWidget(self.companyWidget)
        self.prvPersonWidget = QtWidgets.QWidget(clientDialog)
        self.prvPersonWidget.setObjectName("prvPersonWidget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.prvPersonWidget)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.prvNameLabel = QtWidgets.QLabel(self.prvPersonWidget)
        self.prvNameLabel.setObjectName("prvNameLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.prvNameLabel)
        self.prvNameLineEdit = QtWidgets.QLineEdit(self.prvPersonWidget)
        self.prvNameLineEdit.setObjectName("prvNameLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.prvNameLineEdit)
        self.prvSurnameLineEdit = QtWidgets.QLineEdit(self.prvPersonWidget)
        self.prvSurnameLineEdit.setObjectName("prvSurnameLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.prvSurnameLineEdit)
        self.prvSurnameLabel = QtWidgets.QLabel(self.prvPersonWidget)
        self.prvSurnameLabel.setObjectName("prvSurnameLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.prvSurnameLabel)
        self.prvPESELLineEdit = QtWidgets.QLineEdit(self.prvPersonWidget)
        self.prvPESELLineEdit.setObjectName("prvPESELLineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.prvPESELLineEdit)
        self.prvPESELLabel = QtWidgets.QLabel(self.prvPersonWidget)
        self.prvPESELLabel.setObjectName("prvPESELLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.prvPESELLabel)
        self.prvAddressLineEdit = QtWidgets.QLineEdit(self.prvPersonWidget)
        self.prvAddressLineEdit.setObjectName("prvAddressLineEdit")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.prvAddressLineEdit)
        self.prvAdressLabel = QtWidgets.QLabel(self.prvPersonWidget)
        self.prvAdressLabel.setObjectName("prvAdressLabel")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.prvAdressLabel)
        self.verticalLayout.addWidget(self.prvPersonWidget)
        self.clientDialogButtonsLayout = QtWidgets.QHBoxLayout()
        self.clientDialogButtonsLayout.setObjectName("clientDialogButtonsLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.clientDialogButtonsLayout.addItem(spacerItem)
        self.clientOkButton = QtWidgets.QPushButton(clientDialog)
        self.clientOkButton.setObjectName("clientOkButton")
        self.clientDialogButtonsLayout.addWidget(self.clientOkButton)
        self.clientCancelButton = QtWidgets.QPushButton(clientDialog)
        self.clientCancelButton.setObjectName("clientCancelButton")
        self.clientDialogButtonsLayout.addWidget(self.clientCancelButton)
        self.verticalLayout.addLayout(self.clientDialogButtonsLayout)

        self.retranslateUi(clientDialog)
        QtCore.QMetaObject.connectSlotsByName(clientDialog)

    def retranslateUi(self, clientDialog):
        _translate = QtCore.QCoreApplication.translate
        clientDialog.setWindowTitle(_translate("clientDialog", "Dialog"))
        self.clientTypeComboBox.setItemText(0, _translate("clientDialog", "Osoba prywatna"))
        self.clientTypeComboBox.setItemText(1, _translate("clientDialog", "Firma"))
        self.cmpNameLabel.setText(_translate("clientDialog", "Nazwa:"))
        self.cmpNIPLabel.setText(_translate("clientDialog", "NIP:"))
        self.cmpAddressLabel.setText(_translate("clientDialog", "Adres:"))
        self.prvNameLabel.setText(_translate("clientDialog", "Imię:"))
        self.prvSurnameLabel.setText(_translate("clientDialog", "Nazwisko:"))
        self.prvPESELLabel.setText(_translate("clientDialog", "PESEL:"))
        self.prvAdressLabel.setText(_translate("clientDialog", "Adres:"))
        self.clientOkButton.setText(_translate("clientDialog", "OK"))
        self.clientCancelButton.setText(_translate("clientDialog", "Anuluj"))

