# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientEditDialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_clientEditDialog(object):
    def setupUi(self, clientEditDialog):
        clientEditDialog.setObjectName("clientEditDialog")
        clientEditDialog.resize(253, 273)
        self.gridLayout = QtWidgets.QGridLayout(clientEditDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.companyWidget = QtWidgets.QWidget(clientEditDialog)
        self.companyWidget.setObjectName("companyWidget")
        self.formLayout = QtWidgets.QFormLayout(self.companyWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.cmpNameLabel = QtWidgets.QLabel(self.companyWidget)
        self.cmpNameLabel.setObjectName("cmpNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cmpNameLabel)
        self.cmpNameLineEdit = QtWidgets.QLineEdit(self.companyWidget)
        self.cmpNameLineEdit.setObjectName("cmpNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmpNameLineEdit)
        self.cmpNIPLabel = QtWidgets.QLabel(self.companyWidget)
        self.cmpNIPLabel.setObjectName("cmpNIPLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cmpNIPLabel)
        self.cmpNIPLineEdit = QtWidgets.QLineEdit(self.companyWidget)
        self.cmpNIPLineEdit.setObjectName("cmpNIPLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmpNIPLineEdit)
        self.cmpAddressLabel = QtWidgets.QLabel(self.companyWidget)
        self.cmpAddressLabel.setObjectName("cmpAddressLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cmpAddressLabel)
        self.cmpAddressLineEdit = QtWidgets.QLineEdit(self.companyWidget)
        self.cmpAddressLineEdit.setObjectName("cmpAddressLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmpAddressLineEdit)
        self.gridLayout.addWidget(self.companyWidget, 1, 0, 1, 1)
        self.prvPersonWidget = QtWidgets.QWidget(clientEditDialog)
        self.prvPersonWidget.setObjectName("prvPersonWidget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.prvPersonWidget)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.prvNameLabel = QtWidgets.QLabel(self.prvPersonWidget)
        self.prvNameLabel.setObjectName("prvNameLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.prvNameLabel)
        self.prvNameLineEdit = QtWidgets.QLineEdit(self.prvPersonWidget)
        self.prvNameLineEdit.setObjectName("prvNameLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.prvNameLineEdit)
        self.prvSurnameLineEdit = QtWidgets.QLineEdit(self.prvPersonWidget)
        self.prvSurnameLineEdit.setObjectName("prvSurnameLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.prvSurnameLineEdit)
        self.prvSurnameLabel = QtWidgets.QLabel(self.prvPersonWidget)
        self.prvSurnameLabel.setObjectName("prvSurnameLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.prvSurnameLabel)
        self.prvPESELLineEdit = QtWidgets.QLineEdit(self.prvPersonWidget)
        self.prvPESELLineEdit.setObjectName("prvPESELLineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.prvPESELLineEdit)
        self.prvPESELLabel = QtWidgets.QLabel(self.prvPersonWidget)
        self.prvPESELLabel.setObjectName("prvPESELLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.prvPESELLabel)
        self.prvAddressLineEdit = QtWidgets.QLineEdit(self.prvPersonWidget)
        self.prvAddressLineEdit.setObjectName("prvAddressLineEdit")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.prvAddressLineEdit)
        self.prvAdressLabel = QtWidgets.QLabel(self.prvPersonWidget)
        self.prvAdressLabel.setObjectName("prvAdressLabel")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.prvAdressLabel)
        self.gridLayout.addWidget(self.prvPersonWidget, 2, 0, 1, 1)
        self.clientDialogButtonsLayout = QtWidgets.QHBoxLayout()
        self.clientDialogButtonsLayout.setObjectName("clientDialogButtonsLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.clientDialogButtonsLayout.addItem(spacerItem)
        self.clientEditOkButton = QtWidgets.QPushButton(clientEditDialog)
        self.clientEditOkButton.setObjectName("clientEditOkButton")
        self.clientDialogButtonsLayout.addWidget(self.clientEditOkButton)
        self.clientEditCancelButton = QtWidgets.QPushButton(clientEditDialog)
        self.clientEditCancelButton.setObjectName("clientEditCancelButton")
        self.clientDialogButtonsLayout.addWidget(self.clientEditCancelButton)
        self.gridLayout.addLayout(self.clientDialogButtonsLayout, 3, 0, 1, 1)

        self.retranslateUi(clientEditDialog)
        QtCore.QMetaObject.connectSlotsByName(clientEditDialog)

    def retranslateUi(self, clientEditDialog):
        _translate = QtCore.QCoreApplication.translate
        clientEditDialog.setWindowTitle(_translate("clientEditDialog", "Dialog"))
        self.cmpNameLabel.setText(_translate("clientEditDialog", "Nazwa:"))
        self.cmpNIPLabel.setText(_translate("clientEditDialog", "NIP:"))
        self.cmpAddressLabel.setText(_translate("clientEditDialog", "Adres:"))
        self.prvNameLabel.setText(_translate("clientEditDialog", "Imię:"))
        self.prvSurnameLabel.setText(_translate("clientEditDialog", "Nazwisko:"))
        self.prvPESELLabel.setText(_translate("clientEditDialog", "PESEL:"))
        self.prvAdressLabel.setText(_translate("clientEditDialog", "Adres:"))
        self.clientEditOkButton.setText(_translate("clientEditDialog", "OK"))
        self.clientEditCancelButton.setText(_translate("clientEditDialog", "Anuluj"))

