# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1223, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabZamowienia = QtWidgets.QWidget()
        self.tabZamowienia.setObjectName("tabZamowienia")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabZamowienia)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.orderAddButton = QtWidgets.QPushButton(self.tabZamowienia)
        self.orderAddButton.setObjectName("orderAddButton")
        self.horizontalLayout_1.addWidget(self.orderAddButton)
        self.orderEditButton = QtWidgets.QPushButton(self.tabZamowienia)
        self.orderEditButton.setObjectName("orderEditButton")
        self.horizontalLayout_1.addWidget(self.orderEditButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem)
        self.verticalLayout_1.addLayout(self.horizontalLayout_1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.tabZamowienia)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.orderSerachLineEdit = QtWidgets.QLineEdit(self.tabZamowienia)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderSerachLineEdit.sizePolicy().hasHeightForWidth())
        self.orderSerachLineEdit.setSizePolicy(sizePolicy)
        self.orderSerachLineEdit.setMinimumSize(QtCore.QSize(350, 0))
        self.orderSerachLineEdit.setObjectName("orderSerachLineEdit")
        self.horizontalLayout.addWidget(self.orderSerachLineEdit)
        self.orderSearchComboBox = QtWidgets.QComboBox(self.tabZamowienia)
        self.orderSearchComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.orderSearchComboBox.setObjectName("orderSearchComboBox")
        self.orderSearchComboBox.addItem("")
        self.orderSearchComboBox.addItem("")
        self.orderSearchComboBox.addItem("")
        self.orderSearchComboBox.addItem("")
        self.orderSearchComboBox.addItem("")
        self.orderSearchComboBox.addItem("")
        self.horizontalLayout.addWidget(self.orderSearchComboBox)
        self.orderSearchButton = QtWidgets.QPushButton(self.tabZamowienia)
        self.orderSearchButton.setCheckable(False)
        self.orderSearchButton.setObjectName("orderSearchButton")
        self.horizontalLayout.addWidget(self.orderSearchButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.tabZamowienia)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.orderStateComboBox = QtWidgets.QComboBox(self.tabZamowienia)
        self.orderStateComboBox.setObjectName("orderStateComboBox")
        self.orderStateComboBox.addItem("")
        self.orderStateComboBox.addItem("")
        self.orderStateComboBox.addItem("")
        self.orderStateComboBox.addItem("")
        self.orderStateComboBox.addItem("")
        self.orderStateComboBox.addItem("")
        self.horizontalLayout.addWidget(self.orderStateComboBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.tabZamowienia)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.ordersFromDateEdit = QtWidgets.QDateEdit(self.tabZamowienia)
        self.ordersFromDateEdit.setObjectName("ordersFromDateEdit")
        self.horizontalLayout.addWidget(self.ordersFromDateEdit)
        self.label_4 = QtWidgets.QLabel(self.tabZamowienia)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.ordersToDateEdit = QtWidgets.QDateEdit(self.tabZamowienia)
        self.ordersToDateEdit.setObjectName("ordersToDateEdit")
        self.horizontalLayout.addWidget(self.ordersToDateEdit)
        self.verticalLayout_1.addLayout(self.horizontalLayout)
        self.orderTableView = QtWidgets.QTableWidget(self.tabZamowienia)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderTableView.sizePolicy().hasHeightForWidth())
        self.orderTableView.setSizePolicy(sizePolicy)
        self.orderTableView.setMinimumSize(QtCore.QSize(700, 0))
        self.orderTableView.setObjectName("orderTableView")
        self.orderTableView.setColumnCount(7)
        self.orderTableView.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableView.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableView.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableView.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableView.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableView.setHorizontalHeaderItem(6, item)
        self.orderTableView.horizontalHeader().setCascadingSectionResizes(False)
        self.orderTableView.horizontalHeader().setDefaultSectionSize(100)
        self.orderTableView.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_1.addWidget(self.orderTableView)
        self.verticalLayout_1.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.verticalLayout_1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabZamowienia, "")
        self.tabKlienci = QtWidgets.QWidget()
        self.tabKlienci.setObjectName("tabKlienci")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabKlienci)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.clientAddButton = QtWidgets.QPushButton(self.tabKlienci)
        self.clientAddButton.setObjectName("clientAddButton")
        self.horizontalLayout_5.addWidget(self.clientAddButton)
        self.clientEditButton = QtWidgets.QPushButton(self.tabKlienci)
        self.clientEditButton.setObjectName("clientEditButton")
        self.horizontalLayout_5.addWidget(self.clientEditButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.tabKlienci)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.clientSearchLineEdit = QtWidgets.QLineEdit(self.tabKlienci)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientSearchLineEdit.sizePolicy().hasHeightForWidth())
        self.clientSearchLineEdit.setSizePolicy(sizePolicy)
        self.clientSearchLineEdit.setMinimumSize(QtCore.QSize(350, 0))
        self.clientSearchLineEdit.setObjectName("clientSearchLineEdit")
        self.horizontalLayout_6.addWidget(self.clientSearchLineEdit)
        self.clientSearchButton = QtWidgets.QPushButton(self.tabKlienci)
        self.clientSearchButton.setCheckable(False)
        self.clientSearchButton.setObjectName("clientSearchButton")
        self.horizontalLayout_6.addWidget(self.clientSearchButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.label1 = QtWidgets.QLabel(self.tabKlienci)
        self.label1.setObjectName("label1")
        self.horizontalLayout_6.addWidget(self.label1)
        self.clientStatusComboBox = QtWidgets.QComboBox(self.tabKlienci)
        self.clientStatusComboBox.setObjectName("clientStatusComboBox")
        self.clientStatusComboBox.addItem("")
        self.clientStatusComboBox.addItem("")
        self.clientStatusComboBox.addItem("")
        self.clientStatusComboBox.addItem("")
        self.clientStatusComboBox.addItem("")
        self.clientStatusComboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.clientStatusComboBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.label_31 = QtWidgets.QLabel(self.tabKlienci)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_6.addWidget(self.label_31)
        self.clientFromDateEdit = QtWidgets.QDateEdit(self.tabKlienci)
        self.clientFromDateEdit.setObjectName("clientFromDateEdit")
        self.horizontalLayout_6.addWidget(self.clientFromDateEdit)
        self.label_41 = QtWidgets.QLabel(self.tabKlienci)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_6.addWidget(self.label_41)
        self.clientToDateEdit = QtWidgets.QDateEdit(self.tabKlienci)
        self.clientToDateEdit.setObjectName("clientToDateEdit")
        self.horizontalLayout_6.addWidget(self.clientToDateEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.clientTableView = QtWidgets.QTableWidget(self.tabKlienci)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientTableView.sizePolicy().hasHeightForWidth())
        self.clientTableView.setSizePolicy(sizePolicy)
        self.clientTableView.setMinimumSize(QtCore.QSize(700, 0))
        self.clientTableView.setObjectName("clientTableView")
        self.clientTableView.setColumnCount(6)
        self.clientTableView.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.clientTableView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientTableView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientTableView.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientTableView.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientTableView.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientTableView.setHorizontalHeaderItem(5, item)
        self.clientTableView.horizontalHeader().setCascadingSectionResizes(False)
        self.clientTableView.horizontalHeader().setDefaultSectionSize(100)
        self.clientTableView.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.clientTableView)
        self.verticalLayout_5.setStretch(2, 1)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabKlienci, "")
        self.tabOferta = QtWidgets.QWidget()
        self.tabOferta.setObjectName("tabOferta")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabOferta)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.offerTreeViewLabel = QtWidgets.QLabel(self.tabOferta)
        self.offerTreeViewLabel.setObjectName("offerTreeViewLabel")
        self.gridLayout_3.addWidget(self.offerTreeViewLabel, 0, 0, 1, 1)
        self.offerTreeView = QtWidgets.QTreeView(self.tabOferta)
        self.offerTreeView.setObjectName("offerTreeView")
        self.gridLayout_3.addWidget(self.offerTreeView, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabOferta, "")
        self.tabRaporty = QtWidgets.QWidget()
        self.tabRaporty.setObjectName("tabRaporty")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabRaporty)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.montReportLayout = QtWidgets.QVBoxLayout()
        self.montReportLayout.setObjectName("montReportLayout")
        self.label_6 = QtWidgets.QLabel(self.tabRaporty)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.montReportLayout.addWidget(self.label_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.montReportLayout.addItem(spacerItem6)
        self.monthReportDateSearchLayout = QtWidgets.QHBoxLayout()
        self.monthReportDateSearchLayout.setObjectName("monthReportDateSearchLayout")
        self.monthReportStartLabel = QtWidgets.QLabel(self.tabRaporty)
        self.monthReportStartLabel.setObjectName("monthReportStartLabel")
        self.monthReportDateSearchLayout.addWidget(self.monthReportStartLabel)
        self.monthReportStartDateEdit = QtWidgets.QDateEdit(self.tabRaporty)
        self.monthReportStartDateEdit.setObjectName("monthReportStartDateEdit")
        self.monthReportDateSearchLayout.addWidget(self.monthReportStartDateEdit)
        self.monthReportEndLabel = QtWidgets.QLabel(self.tabRaporty)
        self.monthReportEndLabel.setObjectName("monthReportEndLabel")
        self.monthReportDateSearchLayout.addWidget(self.monthReportEndLabel)
        self.monthReportEndDateEdit = QtWidgets.QDateEdit(self.tabRaporty)
        self.monthReportEndDateEdit.setObjectName("monthReportEndDateEdit")
        self.monthReportDateSearchLayout.addWidget(self.monthReportEndDateEdit)
        self.monthReportShowButton = QtWidgets.QPushButton(self.tabRaporty)
        self.monthReportShowButton.setObjectName("monthReportShowButton")
        self.monthReportDateSearchLayout.addWidget(self.monthReportShowButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.monthReportDateSearchLayout.addItem(spacerItem7)
        self.montReportLayout.addLayout(self.monthReportDateSearchLayout)
        self.monthReportTable = QtWidgets.QTableWidget(self.tabRaporty)
        self.monthReportTable.setObjectName("monthReportTable")
        self.monthReportTable.setColumnCount(3)
        self.monthReportTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.monthReportTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthReportTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthReportTable.setHorizontalHeaderItem(2, item)
        self.monthReportTable.horizontalHeader().setCascadingSectionResizes(True)
        self.monthReportTable.horizontalHeader().setDefaultSectionSize(150)
        self.monthReportTable.horizontalHeader().setMinimumSectionSize(50)
        self.monthReportTable.horizontalHeader().setStretchLastSection(True)
        self.monthReportTable.verticalHeader().setCascadingSectionResizes(True)
        self.monthReportTable.verticalHeader().setDefaultSectionSize(40)
        self.monthReportTable.verticalHeader().setSortIndicatorShown(True)
        self.monthReportTable.verticalHeader().setStretchLastSection(True)
        self.montReportLayout.addWidget(self.monthReportTable)
        self.gridLayout_5.addLayout(self.montReportLayout, 0, 0, 1, 1)
        self.clientReportLayout = QtWidgets.QVBoxLayout()
        self.clientReportLayout.setObjectName("clientReportLayout")
        self.label_7 = QtWidgets.QLabel(self.tabRaporty)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.clientReportLayout.addWidget(self.label_7)
        self.clientReportSearchLayout = QtWidgets.QHBoxLayout()
        self.clientReportSearchLayout.setObjectName("clientReportSearchLayout")
        self.clientReportSearchLabel = QtWidgets.QLabel(self.tabRaporty)
        self.clientReportSearchLabel.setObjectName("clientReportSearchLabel")
        self.clientReportSearchLayout.addWidget(self.clientReportSearchLabel)
        self.clientReportSearchComboBox = QtWidgets.QComboBox(self.tabRaporty)
        self.clientReportSearchComboBox.setObjectName("clientReportSearchComboBox")
        self.clientReportSearchComboBox.addItem("")
        self.clientReportSearchComboBox.addItem("")
        self.clientReportSearchComboBox.addItem("")
        self.clientReportSearchComboBox.addItem("")
        self.clientReportSearchComboBox.addItem("")
        self.clientReportSearchLayout.addWidget(self.clientReportSearchComboBox)
        self.clientReportSearchLineEdit = QtWidgets.QLineEdit(self.tabRaporty)
        self.clientReportSearchLineEdit.setText("")
        self.clientReportSearchLineEdit.setObjectName("clientReportSearchLineEdit")
        self.clientReportSearchLayout.addWidget(self.clientReportSearchLineEdit)
        self.clientReportLayout.addLayout(self.clientReportSearchLayout)
        self.clientReportDateSearchLayout = QtWidgets.QHBoxLayout()
        self.clientReportDateSearchLayout.setObjectName("clientReportDateSearchLayout")
        self.clientReportStartLabel = QtWidgets.QLabel(self.tabRaporty)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientReportStartLabel.sizePolicy().hasHeightForWidth())
        self.clientReportStartLabel.setSizePolicy(sizePolicy)
        self.clientReportStartLabel.setObjectName("clientReportStartLabel")
        self.clientReportDateSearchLayout.addWidget(self.clientReportStartLabel)
        self.clientReportStartDateEdit = QtWidgets.QDateEdit(self.tabRaporty)
        self.clientReportStartDateEdit.setObjectName("clientReportStartDateEdit")
        self.clientReportDateSearchLayout.addWidget(self.clientReportStartDateEdit)
        self.clientReportEndLabel = QtWidgets.QLabel(self.tabRaporty)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientReportEndLabel.sizePolicy().hasHeightForWidth())
        self.clientReportEndLabel.setSizePolicy(sizePolicy)
        self.clientReportEndLabel.setObjectName("clientReportEndLabel")
        self.clientReportDateSearchLayout.addWidget(self.clientReportEndLabel)
        self.clientReportEndDateEdit = QtWidgets.QDateEdit(self.tabRaporty)
        self.clientReportEndDateEdit.setObjectName("clientReportEndDateEdit")
        self.clientReportDateSearchLayout.addWidget(self.clientReportEndDateEdit)
        self.clientReportShowButton = QtWidgets.QPushButton(self.tabRaporty)
        self.clientReportShowButton.setObjectName("clientReportShowButton")
        self.clientReportDateSearchLayout.addWidget(self.clientReportShowButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.clientReportDateSearchLayout.addItem(spacerItem8)
        self.clientReportLayout.addLayout(self.clientReportDateSearchLayout)
        self.clientReportTable = QtWidgets.QTableWidget(self.tabRaporty)
        self.clientReportTable.setObjectName("clientReportTable")
        self.clientReportTable.setColumnCount(5)
        self.clientReportTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.clientReportTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientReportTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientReportTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientReportTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientReportTable.setHorizontalHeaderItem(4, item)
        self.clientReportTable.horizontalHeader().setSortIndicatorShown(True)
        self.clientReportTable.horizontalHeader().setStretchLastSection(True)
        self.clientReportTable.verticalHeader().setCascadingSectionResizes(True)
        self.clientReportTable.verticalHeader().setSortIndicatorShown(True)
        self.clientReportTable.verticalHeader().setStretchLastSection(True)
        self.clientReportLayout.addWidget(self.clientReportTable)
        self.gridLayout_5.addLayout(self.clientReportLayout, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabRaporty, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.orderAddButton.setText(_translate("MainWindow", "Nowe zamówienie"))
        self.orderEditButton.setText(_translate("MainWindow", "Edycja  zamówienia"))
        self.label_2.setText(_translate("MainWindow", "Wyszukiwanie:"))
        self.orderSearchComboBox.setItemText(0, _translate("MainWindow", "ID klienta"))
        self.orderSearchComboBox.setItemText(1, _translate("MainWindow", "Imię"))
        self.orderSearchComboBox.setItemText(2, _translate("MainWindow", "Nazwisko"))
        self.orderSearchComboBox.setItemText(3, _translate("MainWindow", "Nazwa Firmy"))
        self.orderSearchComboBox.setItemText(4, _translate("MainWindow", "PESEL"))
        self.orderSearchComboBox.setItemText(5, _translate("MainWindow", "NIP"))
        self.orderSearchButton.setText(_translate("MainWindow", "LUPA"))
        self.label.setText(_translate("MainWindow", "Pokaż:"))
        self.orderStateComboBox.setItemText(0, _translate("MainWindow", "wszystko"))
        self.orderStateComboBox.setItemText(1, _translate("MainWindow", "zakończone"))
        self.orderStateComboBox.setItemText(2, _translate("MainWindow", "anulowane"))
        self.orderStateComboBox.setItemText(3, _translate("MainWindow", "w trakcie realizacji"))
        self.orderStateComboBox.setItemText(4, _translate("MainWindow", "gotowe"))
        self.orderStateComboBox.setItemText(5, _translate("MainWindow", "złożone"))
        self.label_3.setText(_translate("MainWindow", "Okres od:"))
        self.label_4.setText(_translate("MainWindow", "do:"))
        item = self.orderTableView.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.orderTableView.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Imię"))
        item = self.orderTableView.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nazwisko"))
        item = self.orderTableView.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nazwa Firmy"))
        item = self.orderTableView.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PESEL"))
        item = self.orderTableView.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "NIP"))
        item = self.orderTableView.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Adres"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabZamowienia), _translate("MainWindow", "Zamówienia"))
        self.clientAddButton.setText(_translate("MainWindow", "Nowy klient"))
        self.clientEditButton.setText(_translate("MainWindow", "Edytuj klienta"))
        self.label_11.setText(_translate("MainWindow", "Wyszukiwanie:"))
        self.clientSearchButton.setText(_translate("MainWindow", "Szukaj"))
        self.label1.setText(_translate("MainWindow", "Pokaż:"))
        self.clientStatusComboBox.setItemText(0, _translate("MainWindow", "wszystko"))
        self.clientStatusComboBox.setItemText(1, _translate("MainWindow", "zakończone"))
        self.clientStatusComboBox.setItemText(2, _translate("MainWindow", "anulowane"))
        self.clientStatusComboBox.setItemText(3, _translate("MainWindow", "w trakcie realizacji"))
        self.clientStatusComboBox.setItemText(4, _translate("MainWindow", "gotowe"))
        self.clientStatusComboBox.setItemText(5, _translate("MainWindow", "złożone"))
        self.label_31.setText(_translate("MainWindow", "Okres od:"))
        self.label_41.setText(_translate("MainWindow", "do:"))
        item = self.clientTableView.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.clientTableView.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nazwa klienta"))
        item = self.clientTableView.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Data złożenia"))
        item = self.clientTableView.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Data zakończenia"))
        item = self.clientTableView.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Kwota"))
        item = self.clientTableView.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabKlienci), _translate("MainWindow", "Klienci"))
        self.offerTreeViewLabel.setText(_translate("MainWindow", "Dostępne modele:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOferta), _translate("MainWindow", "Oferta"))
        self.label_6.setText(_translate("MainWindow", "Raporty miesięczne"))
        self.monthReportStartLabel.setText(_translate("MainWindow", "Okres od:"))
        self.monthReportEndLabel.setText(_translate("MainWindow", "do:"))
        self.monthReportShowButton.setText(_translate("MainWindow", "Pokaż raporty"))
        self.monthReportTable.setSortingEnabled(True)
        item = self.monthReportTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Rok"))
        item = self.monthReportTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Miesiąc"))
        item = self.monthReportTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Suma"))
        self.label_7.setText(_translate("MainWindow", "Raporty klienta"))
        self.clientReportSearchLabel.setText(_translate("MainWindow", "Szukaj"))
        self.clientReportSearchComboBox.setItemText(0, _translate("MainWindow", "ID Klienta"))
        self.clientReportSearchComboBox.setItemText(1, _translate("MainWindow", "Imię i nazwisko"))
        self.clientReportSearchComboBox.setItemText(2, _translate("MainWindow", "Nazwa firmy"))
        self.clientReportSearchComboBox.setItemText(3, _translate("MainWindow", "PESEL"))
        self.clientReportSearchComboBox.setItemText(4, _translate("MainWindow", "NIP"))
        self.clientReportStartLabel.setText(_translate("MainWindow", "Okres od:"))
        self.clientReportEndLabel.setText(_translate("MainWindow", "do:"))
        self.clientReportShowButton.setText(_translate("MainWindow", "Pokaż raporty"))
        item = self.clientReportTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID klienta"))
        item = self.clientReportTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nazwa klienta"))
        item = self.clientReportTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Miesiąc"))
        item = self.clientReportTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Rok"))
        item = self.clientReportTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Suma"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRaporty), _translate("MainWindow", "Raporty"))

