# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'positionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_positionDialog(object):
    def setupUi(self, positionDialog):
        positionDialog.setObjectName("positionDialog")
        positionDialog.resize(334, 422)
        self.gridLayout = QtWidgets.QGridLayout(positionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.modelSelector = QtWidgets.QWidget(positionDialog)
        self.modelSelector.setObjectName("modelSelector")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.modelSelector)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modelSelectLabel = QtWidgets.QLabel(self.modelSelector)
        self.modelSelectLabel.setObjectName("modelSelectLabel")
        self.horizontalLayout.addWidget(self.modelSelectLabel)
        self.modelSelectComboBox = QtWidgets.QComboBox(self.modelSelector)
        self.modelSelectComboBox.setObjectName("modelSelectComboBox")
        self.horizontalLayout.addWidget(self.modelSelectComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.modelSelector, 0, 0, 1, 1)
        self.segmentSelector = QtWidgets.QWidget(positionDialog)
        self.segmentSelector.setObjectName("segmentSelector")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.segmentSelector)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.segmentSelectLabel = QtWidgets.QLabel(self.segmentSelector)
        self.segmentSelectLabel.setObjectName("segmentSelectLabel")
        self.horizontalLayout_2.addWidget(self.segmentSelectLabel)
        self.segmentSelectComboBox = QtWidgets.QComboBox(self.segmentSelector)
        self.segmentSelectComboBox.setObjectName("segmentSelectComboBox")
        self.horizontalLayout_2.addWidget(self.segmentSelectComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.segmentSelectLabel.raise_()
        self.segmentSelectComboBox.raise_()
        self.gridLayout.addWidget(self.segmentSelector, 1, 0, 1, 1)
        self.parametersSelector = QtWidgets.QWidget(positionDialog)
        self.parametersSelector.setObjectName("parametersSelector")
        self.formLayout_2 = QtWidgets.QFormLayout(self.parametersSelector)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.segmentQuantityLabel = QtWidgets.QLabel(self.parametersSelector)
        self.segmentQuantityLabel.setObjectName("segmentQuantityLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.segmentQuantityLabel)
        self.segmentQuantitySpinBox = QtWidgets.QSpinBox(self.parametersSelector)
        self.segmentQuantitySpinBox.setObjectName("segmentQuantitySpinBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.segmentQuantitySpinBox)
        self.segmentHeightSpinBox = QtWidgets.QDoubleSpinBox(self.parametersSelector)
        self.segmentHeightSpinBox.setObjectName("segmentHeightSpinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.segmentHeightSpinBox)
        self.segmentWidthSpinBox = QtWidgets.QDoubleSpinBox(self.parametersSelector)
        self.segmentWidthSpinBox.setObjectName("segmentWidthSpinBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.segmentWidthSpinBox)
        self.segmentHeightLabel = QtWidgets.QLabel(self.parametersSelector)
        self.segmentHeightLabel.setObjectName("segmentHeightLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.segmentHeightLabel)
        self.segmentWidthLabel = QtWidgets.QLabel(self.parametersSelector)
        self.segmentWidthLabel.setObjectName("segmentWidthLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.segmentWidthLabel)
        self.segmentPaneComboBox = QtWidgets.QComboBox(self.parametersSelector)
        self.segmentPaneComboBox.setObjectName("segmentPaneComboBox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.segmentPaneComboBox)
        self.segmentPaneLabel = QtWidgets.QLabel(self.parametersSelector)
        self.segmentPaneLabel.setObjectName("segmentPaneLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.segmentPaneLabel)
        self.segmentStatusComboBox = QtWidgets.QComboBox(self.parametersSelector)
        self.segmentStatusComboBox.setObjectName("segmentStatusComboBox")
        self.segmentStatusComboBox.addItem("")
        self.segmentStatusComboBox.addItem("")
        self.segmentStatusComboBox.addItem("")
        self.segmentStatusComboBox.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.segmentStatusComboBox)
        self.segmentStatusLabel = QtWidgets.QLabel(self.parametersSelector)
        self.segmentStatusLabel.setObjectName("segmentStatusLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.segmentStatusLabel)
        self.gridLayout.addWidget(self.parametersSelector, 2, 0, 1, 1)
        self.positionDialogButtonsLayout = QtWidgets.QHBoxLayout()
        self.positionDialogButtonsLayout.setObjectName("positionDialogButtonsLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.positionDialogButtonsLayout.addItem(spacerItem2)
        self.positionDialogOkButton = QtWidgets.QPushButton(positionDialog)
        self.positionDialogOkButton.setObjectName("positionDialogOkButton")
        self.positionDialogButtonsLayout.addWidget(self.positionDialogOkButton)
        self.positionDialogCancelButton = QtWidgets.QPushButton(positionDialog)
        self.positionDialogCancelButton.setObjectName("positionDialogCancelButton")
        self.positionDialogButtonsLayout.addWidget(self.positionDialogCancelButton)
        self.gridLayout.addLayout(self.positionDialogButtonsLayout, 3, 0, 1, 1)

        self.retranslateUi(positionDialog)
        QtCore.QMetaObject.connectSlotsByName(positionDialog)

    def retranslateUi(self, positionDialog):
        _translate = QtCore.QCoreApplication.translate
        positionDialog.setWindowTitle(_translate("positionDialog", "Dialog"))
        self.modelSelectLabel.setText(_translate("positionDialog", "Model:"))
        self.segmentSelectLabel.setText(_translate("positionDialog", "Segment:"))
        self.segmentQuantityLabel.setText(_translate("positionDialog", "Ilość:"))
        self.segmentHeightLabel.setText(_translate("positionDialog", "Wysokość:"))
        self.segmentWidthLabel.setText(_translate("positionDialog", "Szerokość:"))
        self.segmentPaneLabel.setText(_translate("positionDialog", "Rodzaj szyby:"))
        self.segmentStatusComboBox.setItemText(0, _translate("positionDialog", "Zlozone"))
        self.segmentStatusComboBox.setItemText(1, _translate("positionDialog", "W trakcie realizacji"))
        self.segmentStatusComboBox.setItemText(2, _translate("positionDialog", "Wyslane/odebrane"))
        self.segmentStatusComboBox.setItemText(3, _translate("positionDialog", "Zrealizowane"))
        self.segmentStatusLabel.setText(_translate("positionDialog", "Status:"))
        self.positionDialogOkButton.setText(_translate("positionDialog", "Ok"))
        self.positionDialogCancelButton.setText(_translate("positionDialog", "Anuluj"))

